"""Transparency label generation — the plain-language badge a reader sees.

Three variants. The AI label requires MORE confidence than the human label
(config.HIGH_CONF_AI > config.HIGH_CONF_HUMAN) because falsely branding a human
writer as AI is the worst outcome on a creative platform. Anything that clears
neither bar falls to "uncertain".

The exact strings below are reproduced verbatim in the README.
"""

from __future__ import annotations

from . import config

# Body templates use {pct} = round(confidence * 100).
_AI_BODY = (
    "Our checks suggest this text was probably generated by AI "
    "(confidence: {pct}%). This is an automated estimate, not a certainty. "
    "If you wrote this yourself, you can appeal and a human will review it."
)
_HUMAN_BODY = (
    "Our checks found no strong signs of AI generation (confidence: {pct}%). "
    "This is an automated estimate and not a guarantee of authorship."
)
_UNCERTAIN_BODY = (
    "Our checks were inconclusive for this text (confidence: {pct}%). "
    "We can't reliably say whether it was written by a human or AI, so we're "
    "not labeling it either way. Short pieces and unusual styles are especially "
    "hard to judge."
)


def build_label(attribution: str, confidence: float, ai_score: float) -> dict:
    """Return {variant, title, body} for the given decision."""
    pct = round(confidence * 100)

    ai_confident = ai_score >= config.AI_THRESHOLD and confidence >= config.HIGH_CONF_AI
    human_confident = ai_score <= config.HUMAN_THRESHOLD and confidence >= config.HIGH_CONF_HUMAN

    if ai_confident:
        return {
            "variant": "high_confidence_ai",
            "title": "🤖 Likely AI-generated",
            "body": _AI_BODY.format(pct=pct),
        }
    if human_confident:
        return {
            "variant": "high_confidence_human",
            "title": "✍️ Likely human-written",
            "body": _HUMAN_BODY.format(pct=pct),
        }
    return {
        "variant": "uncertain",
        "title": "❓ Attribution uncertain",
        "body": _UNCERTAIN_BODY.format(pct=pct),
    }
