"""Signal 1 — LLM classifier via Groq (llama-3.3-70b-versatile).

Asks the model to holistically judge how AI-like a piece of text reads and
return a probability plus a one-sentence rationale. This captures *semantic and
stylistic* coherence that structural statistics miss.

Graceful degradation: if no API key is configured, the key is invalid, or the
call fails/parses badly, the signal reports ``available: False`` and the
pipeline falls back to stylometry alone (recording that it did so).
"""

from __future__ import annotations

import json
import os

from . import config

_PROMPT = """You are a forensic text-attribution assistant for a creative writing platform.
Assess whether the following text was written by a human or generated by an AI language model.
Judge holistically: cliché density, generic "assistant" phrasing, tonal uniformity, and whether
the voice feels idiosyncratically human. You have NO ground truth; give your best calibrated estimate.

Respond with ONLY a JSON object, no prose:
{{"ai_probability": <float 0..1, where 1 = almost certainly AI>, "reasoning": "<one short sentence>"}}

TEXT:
\"\"\"
{text}
\"\"\"
"""


def _get_client():
    """Return a Groq client, or None if no usable key is configured."""
    key = os.environ.get("GROQ_API_KEY", "").strip()
    # Reject empty or obvious placeholder keys so we degrade cleanly.
    if not key or key.lower().startswith(("your", "sk-xxx", "placeholder")):
        return None
    try:
        from groq import Groq

        return Groq(api_key=key, timeout=config.LLM_TIMEOUT_SECONDS)
    except Exception:
        return None


def analyze_llm(text: str) -> dict:
    """Return the LLM signal.

    Output shape (available):
        {"name":"llm","available":True,"ai_probability":float,"reasoning":str,"model":...}
    Output shape (unavailable):
        {"name":"llm","available":False,"reason":str}
    """
    client = _get_client()
    if client is None:
        return {
            "name": "llm",
            "available": False,
            "reason": "No valid GROQ_API_KEY configured; using stylometry only.",
        }

    try:
        resp = client.chat.completions.create(
            model=config.GROQ_MODEL,
            messages=[{"role": "user", "content": _PROMPT.format(text=text)}],
            temperature=0,
            max_tokens=150,
            response_format={"type": "json_object"},
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
        prob = float(data["ai_probability"])
        prob = max(0.0, min(1.0, prob))
        return {
            "name": "llm",
            "available": True,
            "ai_probability": round(prob, 4),
            "reasoning": str(data.get("reasoning", "")).strip()[:280],
            "model": config.GROQ_MODEL,
        }
    except Exception as exc:  # network error, bad JSON, missing field, etc.
        return {
            "name": "llm",
            "available": False,
            "reason": f"LLM call failed ({type(exc).__name__}); using stylometry only.",
        }
